function [A, B, ind] = BipartiteGraph_YU(X,anchor_rate,opts,Graph)
% Input:
%       - X: the data matrix of size nSmp * nFea * nView, where each row is a sample
%               point;
%       - anchor_rate: the rate of sampling data points as anchors;
%       - opts: options for this algorithm
%           - k: Near neighbor number;
%           - style:
%               - '0': use DAS;
%               - '1': use VAS;
%               - '2': use randomly sampled points from the original data set;
%               - '3': use the nearest point of each cluster center generated by kmeans;
%               - '4': use centers of clusters generated by kmeans;

% Output:
%       - A: the selected anchors;
%       - B: Constructed Bipartite Graph for Each View
%
%   Written by Yu Wenjun

if ~exist('Graph','var')
    Graph = 1;
end
k =10;
style = 2;
if isfield(opts, 'k');   k = opts. k;  end
if isfield(opts, 'style');    style = opts. style;   end
n_View = length(X);
n = size(X{1},1);
XX = [];
for v = 1:length(X)
    XX = [XX X{v}];
end
m = fix(n*anchor_rate);
B = cell(n_View,1);
A = cell(n_View,1);
%%
%%==============Anchor Selection=========%%
if style == 0 % DAS
    [~,ind,~] = graphgen_anchor(XX,m);
    for v = 1:n_View
        A{v} = X{v}(ind,:);
    end
elseif style == 3 % VDA
    [~,ind,~] = VDA(XX,m);
    for v = 1:n_View
        A{v} = X{v}(ind, :);
    end
elseif style == 4 % rand sample
    vec = randperm(n);
    ind = vec(1:m);
    for v = 1:n_View
        A{v} = X{v}(ind, :);
    end
elseif style == 5 % KNP
    XX = [];
    for v = 1:n_View
        XX = [XX X{v}];
    end
    [~, ~, ~, ~, dis] = litekmeans(XX, m);
    [~,ind] = min(dis,[],1);
    ind = sort(ind,'ascend');
    for v = 1:n_View
        A{v} = X{v}(ind, :);
    end
elseif style == 6 % kmeans sample
    XX = [];
    for v = 1:n_View
        XX = [XX X{v}];
        len(v) = size(X{v},2);
    end
    [~, Cen, ~, ~, ~] = litekmeans(XX, m);
    t1 = 1;
    for v=1:n_View
        t2 = t1+len(v)-1;
        A{v} = Cen(:,t1:t2);
        t1 = t2+1;
    end
end
%%
%%==========Bipartite Graph Inilization for Each View=========%%
if Graph == 1
    for v = 1:n_View
        D = L2_distance_1(X{v}', A{v}');
        [~, idx] = sort(D, 2); % sort each row
        B{v} = zeros(n,m);
        for ii = 1:n
            id = idx(ii,1:k+1);
            di = D(ii, id);
            B{v}(ii,id) = (di(k+1)-di)/(k*di(k+1)-sum(di(1:k))+eps);
        end
        
        % [~, idx1] = sort(D, 1); % sort each column
        % B1{v} = zeros(n,m);
        % for ii = 1:m
        %     id1 = idx1(1:k+1,ii);
        %     di = D(id1,ii);
        %     B1{v}(id1,ii) = (di(k+1)-di)/(k*di(k+1)-sum(di(1:k))+eps);
        % end
        % B{v} = (B{v}+B1{v})/2;
    end
end
end
